### ISSUE TITLE
Can't add noname mmc

### ISSUE THREAD

**Issue by Jacobtey** [aluzzardi/pam_usb#37]
jacobtey@jacobtey-laptop ~ % sudo pamusb-conf --add-device MMCKEY                                                                                       
Please select the device you wish to add.
* Using " 000000 (b70c3fcb)" (only option)

Which volume would you like to use for storing data ?
* Using "/dev/mmcblk0p1 (UUID: 74AF-FABE)" (only option)

Name            : MMCKEY
Vendor          : Unknown
Model           : 000000
Serial          : b70c3fcb
UUID            : 74AF-FABE

Save to /etc/pamusb.conf ?
[Y/n]
Traceback (most recent call last):
  File "/usr/bin/pamusb-conf", line 267, in <module>
    addDevice(options)
  File "/usr/bin/pamusb-conf", line 203, in addDevice
    for name, value in (('vendor', device.vendor),
AttributeError: Element instance has no attribute 'vendor'

**Comment by hacker1024** [comment]
I have this problem too, with a USB drive.

```
Please select the device you wish to add.
* Using "USB 2.0 Flash Drive (169D846F)" (only option)

Which volume would you like to use for storing data ?
* Using "/dev/sdd1 (UUID: 807F-D06A)" (only option)

Name		: hacker1024
Vendor		: USB 2.0
Model		: Flash Drive
Serial		: 169D846F
UUID		: 807F-D06A

Save to /etc/security/pam_usb.conf ?
[Y/n] 
Traceback (most recent call last):
  File "/usr/bin/pamusb-conf", line 266, in <module>
    addDevice(options)
  File "/usr/bin/pamusb-conf", line 204, in addDevice
    for name, value in (('vendor', device.vendor),
AttributeError: Element instance has no attribute 'vendor'
```
