### ISSUE TITLE
An error occurs when pamusb-conf are executed in  centos8 and ubuntu18.04

### ISSUE THREAD

**Issue by likunyur** [aluzzardi/pam_usb#52]
In these two systems, execute "pamusb conf  --add device=MyDevice", and the prompt is as follows:

  Traceback (most recent call last):
  File "/usr/bin/pamusb-conf", line 264, in <module>
    '/org/freedesktop/UDisks')
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files

At present, I try to solve the problem of "org. freedesktop. UDisks", but there is no good method，I hope to seek help here to solve this problem.

thanks.

**Comment by galliotxy** [comment]
您好，您的邮件已经收到。我会尽快查收的~
